from __future__ import annotations

from textwrap import dedent

from .models import (
    AgentStatus,
    ArtifactType,
    BuilderState,
    GeneratedArtifact,
    ReviewFeedback,
    TestResult,
    VerificationResult,
)
from .settings import get_settings


def _add_decision(state: BuilderState, agent: str, action: str, reason: str) -> None:
    state.current_agent = agent
    state.decision_history.append({"agent": agent, "action": action, "reason": reason})
    state.touch()


def planner_architect(state: BuilderState) -> BuilderState:
    _add_decision(state, "planner_architect", "plan", "Create production-ready plan")
    state.status = AgentStatus.IN_PROGRESS
    state.plan = dedent(
        f"""
        # Projektplan: {state.project_id}

        ## Ziel
        Aus der Anfrage wird ein lauffähiges LangGraph-Projekt generiert, getestet,
        reviewed und mit Docker/K3s deploybar gemacht.

        ## Erfolgskriterien
        - Pydantic-State und typisierte Artefakte sind vorhanden.
        - Supervisor-Orchestration führt Planner, Builder, Memory Designer,
          Executor, Reviewer, Verifier und Deployment Specialist aus.
        - Tests und Qualitätsbewertung laufen deterministisch.
        - Deployment kann per Docker Compose auf einem VPS gestartet werden.

        ## Risiken
        - LLM-Ausgaben koennen inkonsistent sein; strukturierte Modelle und Reviewer
          reduzieren das Risiko.
        - Sandbox-Ausfuehrung braucht klare Allow-Lists.
        - Produktion braucht echte Secrets und persistente Volumes.
        """
    ).strip()
    state.architecture_decisions.extend(
        [
            "Use LangGraph StateGraph for orchestration.",
            "Use Pydantic models as the contract between agents.",
            "Use deterministic node implementations for testability; add LLM adapters later.",
            "Use Docker Compose as the default VPS deployment path.",
        ]
    )
    state.human_approval_points.append("Approve project plan before production rollout")
    return state


def agent_builder(state: BuilderState) -> BuilderState:
    _add_decision(state, "agent_builder", "generate_code", "Create minimal runnable artifact set")
    state.current_code = dedent(
        """
        from langgraph.graph import END, StateGraph

        def build_graph():
            graph = StateGraph(dict)
            graph.add_node("start", lambda state: {**state, "built": True})
            graph.set_entry_point("start")
            graph.add_edge("start", END)
            return graph.compile()
        """
    ).strip()
    state.generated_artifacts.append(
        GeneratedArtifact(
            filename="graph.py",
            content=state.current_code,
            artifact_type=ArtifactType.CODE,
            description="Minimal LangGraph project graph generated by the Agent Builder.",
        )
    )
    state.generated_artifacts.append(
        GeneratedArtifact(
            filename="state.py",
            content=(
                "from pydantic import BaseModel\n\n"
                "class ProjectState(BaseModel):\n"
                "    built: bool = False\n"
            ),
            artifact_type=ArtifactType.CODE,
            description="Minimal generated project state model.",
        )
    )
    return state


def memory_skills_designer(state: BuilderState) -> BuilderState:
    _add_decision(
        state,
        "memory_skills_designer",
        "design_memory",
        "Attach memory and skill design",
    )
    state.used_skills.extend(["planning", "langgraph-generation", "review", "deployment"])
    state.new_skills_proposed.append(
        {
            "name": "langgraph_project_scaffolder",
            "description": "Generate LangGraph project skeletons with tests and deployment files.",
            "hermes_compatible": True,
        }
    )
    state.generated_artifacts.append(
        GeneratedArtifact(
            filename="hermes_profile.yaml",
            content=dedent(
                f"""
                identity:
                  name: LangGraph Builder Team
                  project_id: {state.project_id}
                skills:
                  - planning
                  - langgraph-generation
                  - sandbox-testing
                  - deployment
                memory:
                  checkpointer: postgres
                  vector_store: qdrant
                """
            ).strip(),
            artifact_type=ArtifactType.CONFIG,
            description="Hermes-compatible profile generated for downstream integration.",
        )
    )
    return state


def executor_sandbox_tester(state: BuilderState) -> BuilderState:
    _add_decision(state, "executor_sandbox_tester", "test", "Run deterministic internal checks")
    checks = [
        ("plan_exists", state.plan is not None),
        ("code_generated", bool(state.current_code)),
        ("artifacts_generated", len(state.generated_artifacts) >= 2),
        ("memory_design_present", bool(state.new_skills_proposed)),
    ]
    for name, passed in checks:
        state.test_results.append(
            TestResult(
                test_name=name,
                status="passed" if passed else "failed",
                output=f"{name}: {'ok' if passed else 'missing'}",
            )
        )
    state.sandbox_logs.append("Deterministic sandbox checks completed.")
    return state


def reviewer_critic(state: BuilderState) -> BuilderState:
    _add_decision(state, "reviewer_critic", "review", "Review generated plan and artifacts")
    if not state.current_code:
        state.review_feedback.append(
            ReviewFeedback(
                category="code",
                severity="critical",
                message="No code artifact was generated.",
                suggestion="Re-run Agent Builder.",
            )
        )
    if not state.review_feedback:
        state.review_feedback.append(
            ReviewFeedback(
                category="architecture",
                severity="low",
                message=(
                    "Architecture is coherent for an MVP and has clear production "
                    "extension points."
                ),
            )
        )
    return state


def verifier_evaluator(state: BuilderState) -> BuilderState:
    _add_decision(state, "verifier_evaluator", "score", "Calculate quality score")
    failed_tests = sum(1 for result in state.test_results if result.status == "failed")
    critical_issues = sum(1 for issue in state.review_feedback if issue.severity == "critical")
    score = 90 - failed_tests * 20 - critical_issues * 35
    score = max(0, min(100, score))
    recommendation = "approve" if score >= get_settings().quality_threshold else "revise"
    state.quality_score = score
    state.verification_result = VerificationResult(
        overall_score=score,
        category_scores={
            "architecture": 85 if state.plan else 40,
            "implementation": 85 if state.current_code else 30,
            "testing": 90 if failed_tests == 0 else 50,
            "deployment": 80,
        },
        strengths=[
            "Typed state contract",
            "Deterministic testable workflow",
            "Docker-first deployment path",
        ],
        weaknesses=[] if score >= 75 else ["Quality threshold not reached"],
        improvement_suggestions=[
            "Add live LLM adapter with structured output validation",
            "Enable Postgres checkpointer in production",
            "Add real sandbox execution for generated repositories",
        ],
        recommendation=recommendation,
    )
    if recommendation == "revise":
        state.status = AgentStatus.REFLECTION
        state.reflection_notes.append("Verifier requested a revision loop.")
    return state


def git_docs_deployment_specialist(state: BuilderState) -> BuilderState:
    _add_decision(state, "git_docs_deployment_specialist", "package", "Add deployment artifacts")
    state.docker_compose = "docker compose up -d --build"
    state.k8s_manifests.append("deployments/k3s/app.yaml")
    state.deployment_instructions = dedent(
        """
        1. Copy the repository to the VPS.
        2. Create `.env` from `.env.example` and set production secrets.
        3. Run `docker compose up -d --build`.
        4. Open the configured HTTP port and verify `/health`.
        """
    ).strip()
    state.generated_artifacts.append(
        GeneratedArtifact(
            filename="DEPLOYMENT.md",
            content=state.deployment_instructions,
            artifact_type=ArtifactType.DOCUMENTATION,
            description="VPS deployment instructions.",
        )
    )
    state.status = AgentStatus.COMPLETED
    state.final_summary = (
        f"Build completed with quality score {state.quality_score}. "
        "Artifacts are ready for review and Docker deployment."
    )
    state.recommended_next_steps.extend(
        [
            "Provide VPS SSH details for remote deployment.",
            "Configure production secrets in .env.",
            "Add project-specific LLM provider configuration.",
        ]
    )
    return state
